plugins {
    id 'com.android.application'
}

android {
    namespace 'pl.krupapiotr.mediaprobe'
    compileSdk 35

    defaultConfig {
        applicationId 'pl.krupapiotr.mediaprobe'
        minSdk 23
        targetSdk 28
        versionCode 6
        versionName '0.6-AUTO'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
